export const QUERY_KEY = {
  GET_CATALOG_REASON: 'GET_CATALOG_REASON',
  GET_ORG_ID: 'GET_ORG_ID',
  GET_LIST_PRODUCTS: 'GET_LIST_PRODUCTS',
  GET_NUMBER: 'GET_NUMBER',
  GET_CHOOSE_PRODUCT: 'GET_CHOOSE_PRODUCT',
  GET_PRODUCT_CATEGORY: 'GET_PRODUCT_CATEGORY',
  GET_TO_SERIAL: 'GET_TO_SERIAL',
  GET_UPLOAD_FILE: 'GET_UPLOAD_FILE',
};
