export const QUERY_KEY = {
    GET_DISTRIBUTE_NUMBER: 'GET_DISTRIBUTE_NUMBER',
    DETAIL_DISTRIBUTE_NUMBER: 'DETAIL_DISTRIBUTE_NUMBER',
    GET_ACTION_SAMPLE: 'GET_ACTION_SAMPLE',
    GET_ORGANZITAION_CURRENT: 'GET_ORGANZITAION_CURRENT',
    GET_STOCK_ISDN: 'GET_STOCK_ISDN',
    GET_LIST_REASON: 'GET_LIST_REASON',
    GET_STOCK_ISDN_ORG: 'GET_STOCK_ISDN_ORG',
    DOWNLOAD_FILE: 'DOWNLOAD_FILE'
}