ARG BASE_BUILDER="harbor.vissoft.vn/vnsky/web-builder"
ARG BASE_RUNNER="harbor.vissoft.vn/vnsky/web-runner"

FROM node:20-alpine AS base
WORKDIR /workspace
COPY package.json ./package.json
COPY yarn.lock ./yarn.lock
COPY .yarnrc.yml ./.yarnrc.yml
# ARG NPM_CONFIG_REGISTRY="https://registry.npmjs.org"
ARG YARN_NPM_REGISTRY_SERVER="https://registry.npmjs.org"

# Cài đặt và cấu hình corepack
RUN npm install -g corepack

# Enable corepack và sử dụng version từ package.json
RUN corepack enable && \
    corepack prepare --activate

# Cấu hình yarn registry và install dependencies
RUN ls -la && \
    echo "Using yarn repo: $YARN_NPM_REGISTRY_SERVER" && \
    # echo "Using npm repo: $NPM_CONFIG_REGISTRY" && \
    yarn config set npmRegistryServer $YARN_NPM_REGISTRY_SERVER && \
    yarn config set npmAlwaysAuth false && \
    yarn config get npmRegistryServer && \
    yarn install --frozen-lockfile

COPY ./nx.json ./nx.json
COPY ./apps/Internal/.env.production ./.env
COPY ./tsconfig.base.json ./tsconfig.base.json
COPY ./jest.config.ts ./jest.config.ts
COPY ./jest.preset.js ./jest.preset.js
COPY ./.eslintrc.json ./.eslintrc.json
COPY ./.eslintignore ./.eslintignore
COPY ./.prettierrc ./.prettierrc
COPY ./.prettierignore ./.prettierignore
COPY ./libs ./libs
COPY ./apps/Internal ./apps/Internal
RUN yarn build:internal

FROM $BASE_RUNNER AS runner
ENV TZ=Asia/Ho_Chi_Minh
WORKDIR /usr/share/nginx/html
COPY --from=base --chown=nginx:nginx /workspace/dist/apps/internal /usr/share/nginx/html
