export const REACT_QUERY_KEYS = {
  //common
  GET_MENU: 'GET_MENU',
  GET_PARAMS_OPTION: 'GET_PARAMS_OPTION',
  GET_PARAMS: 'GET_PARAMS_OPTION',
  GET_PROFILE: 'GET_PROFILE',
  GET_ALL_REASON_CATALOG_SERVICE: 'GET_ALL_REASON_CATALOG_SERVICE',
  // User Management

  // Role Management
  GET_ALL_ROLES: 'GET_ALL_ROLES',
  ROLE_OBJECT_LIST: 'ROLE_OBJECT_LIST',

  //UserGroupManagerKey
  GET_LIST_GROUP: 'GET_LIST_GROUP',
  GET_LIST_OPTION_USER_ACTIVE: 'GET_LIST_OPTION_USER_ACTIVE',
  GET_LIST_OPTION_ROLE_ACTIVE: 'GET_LIST_OPTION_ROLE_ACTIVE',
  //UserKey
  GET_LIST_GROUP_ACTIVE: 'GET_LIST_GROUP_ACTIVE',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_ALL_ADN_BY_AGE: 'GET_ALL_ADN_BY_AGE',
  GET_ALL_ADN_BY_REGION: 'GET_ALL_ADN_BY_REGION',
  // Parameter
  GET_LIST_PARAMETER: 'GET_LIST_PARAMETER',
  // Kit manager
  GET_LIST_KITS: 'GET_LIST_KITS',
  GET_LIST_LOCI_SELECT: 'GET_LIST_LOCI_SELECT',

  // Matching Rules
  GET_ALL_RULES: 'GET_ALL_RULES',
  GET_ALL_LOCIES: 'GET_ALL_LOCIES',

  // Request Management
  GET_ALL_PARAMS_REQUESTS: 'GET_ALL_PARAMS_REQUESTS',
  GET_ALL_REQUESTS: 'GET_ALL_REQUESTS',
  SUB_SYSTEM: 'SUB_SYSTEM',

  // Phân tích ADN SNP
  GET_TRANSITION_ID: 'GET_TRANSITION_ID',

  // Population
  GET_ALL_POPULATION: 'GET_ALL_POPULATION',

  //Tìm kiếm mẫu sủ dụng STR
  GET_MATCHING_RULES: 'GET_MATCHING_RULES',

  //Profile
  GET_USER_INFO: 'GET_USER_INFO',

  //Data Management
  GET_SUBJECT_ID: 'GET_SUBJECT_ID',

  //Drug Response
  GET_DRUG_RESPONSE: 'GET_DRUG_RESPONSE',
  GET_ALL_DRUG_RESPONSE: 'GET_DRUG_RESPONSE',

  //Medium Sick
  GET_MEDIUM_SICK: 'GET_MEDIUM_SICK',
  GET_ALL_MEDIUM_SICK: 'GET_ALL_MEDIUM_SICK',

  //ADNByAge
  GET_LIST_AGE: 'GET_LIST_AGE',

  //ADNByRegion
  GET_LIST_ADN_BY_REGION: 'GET_LIST_ADN_BY_REGION',

  // Exploration
  GET_UNIT_FILTER: 'GET_UNIT_FILTER',
  GET_DATA_SOURCE_FILTER: 'GET_DATA_SOURCE_FILTER',
  GET_SUBJECT: 'GET_SUBJECT',
  GET_COLLECTION_SAMPLE_BY_SUBJECT_ID: 'GET_COLLECTION_SAMPLE_BY_SUBJECT_ID',
  GET_COLLECTION_SAMPLE_BY_UNIT_ID: 'GET_COLLECTION_SAMPLE_BY_UNIT_ID',
  GET_FILE_SAMPLE_BY_COLLECTION_SAMPLE_ID:
    'GET_FILE_SAMPLE_BY_COLLECTION_SAMPLE_ID',
  GET_VARIANT_DETAIL_BY_SAMPLE_CODE: 'GET_VARIANT_DETAIL_BY_SAMPLE_CODE',
  GET_ALL_COLLECTION_FILE: 'GET_ALL_COLLECTION_FILE',
  GET_LIST_COLLECTION_UNIT: 'GET_LIST_COLLECTION_UNIT',
  GET_VARIANT_DETAIL_BY_ID: 'GET_VARIANT_DETAIL_BY_ID',
  GET_SNP_VARIANT_DETAIL_BY_ID: 'GET_SNP_VARIANT_DETAIL_BY_ID',
  GET_LIST_STR_VARIANT: 'GET_LIST_STR_VARIANT',
  GET_LIST_SNP_VARIANT: 'GET_LIST_SNP_VARIANT',

  GET_LIST_ADNPROVINCE: 'GET_LIST_ADNPROVINCE',
  GET_ALL_LIST_ADNPROVINCE: 'GET_ALL_LIST_ADNPROVINCE',

  //File collection ADN
  GET_LIST_FILE_COLLECTION_ADN: 'GET_LIST_FILE_COLLECTION_ADN',

  //Data source
  GET_LIST_DATA_SOURCE: 'GET_LIST_DATA_SOURCE',
  // Quản lý phả hệ
  GET_LIST_GRAPH: 'GET_LIST_GRAPH',
  GET_FAMILY_TREE: 'GET_FAMILY_TREE',
  GET_FAMILY_TREE_LV2: 'GET_FAMILY_TREE_LV2',

  // Danh sách adn profile
  GET_LIST_ADN_PROFILE: 'GET_LIST_ADN_PROFILE',

  // Gen
  GET_GRAPH_GEN: 'GET_GRAPH_GEN',

  //Local sample list
  GET_ALL_LOCAL_SAMPLE: 'GET_ALL_LOCAL_SAMPLE',

  //danh sách yêu cầu chuyển mẫu
  GET_ALL_TRANSFERRED_REQUEST_SAMPLE: 'GET_ALL_TRANSFERRED_REQUEST_SAMPLE',

  //ListOfDepartment
  GET_LIST_OF_DEPARTMENT: 'GET_LIST_OF_DEPARTMENT',
  GET_VIEW_LIST_OF_DEPARTMENT: 'GET_VIEW_LIST_OF_DEPARTMENT',

  // organization
  ORGANIZATION_ALL: 'ORGANIZATION_ALL',
  ORDERS: 'ORDERS',
  PRODUCT_IN_ORDER: 'PRODUCT_IN_ORDER',
  PRODUCT_IN_ORDER_INFINITY_SCROLL: 'PRODUCT_IN_ORDER_INFINITY_SCROLL',

  GET_REASON: 'GET_REASON',
  GET_PARTNER_INFO: 'GET_PARTNER_INFO',
  PRODUCT_TYPE: 'PRODUCT_TYPE',

  // Product Catalog
  GET_LIST_CATEGORY_PRODUCT: 'GET_LIST_CATEGORY_PRODUCT',
  // Serial Lookup
  GET_LIST_SERIAL_LIST: 'GET_LIST_SERIAL_LIST',
  GET_LIST_ORG: 'GET_LIST_ORG',
  GET_LIST_PRODUCTS: 'GET_LIST_PRODUCTS',

  GET_LIST_PARTNER_LIMITS_DEBT_HISTORY: 'GET_LIST_PARTNER_LIMITS_DEBT_HISTORY',
  // Inventory Detail
  INVENTORY_DETAIL: 'INVENTORY_DETAIL',
  GET_LIST_ORG_USE: 'GET_LIST_ORG_USE',
  //  GET_PROFILE_OTHER
  GET_PROFILE_OTHER: 'GET_PROFILE_OTHER',

  // Đổi sim hàng loạt
  GET_SIM_REPLACEMENT_LIST: 'GET_SIM_REPLACEMENT_LIST',
  GET_SIM_REPLACEMENT_DETAIL: 'GET_SIM_REPLACEMENT_DETAIL',
  GET_ALL_ORGANIZATION: 'GET_ALL_ORGANIZATION',
  GET_ORGNIZATION_PARTNER: 'GET_ORGNIZATION_PARTNER',

  DECRYPT_OPERATIONS_ID: 'DECRYPT_OPERATIONS_ID',
};
