export const REACT_QUERY_KEYS = {
  GET_MENU: 'GET_MENU',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_ALL_ROLES: 'GET_ALL_ROLES',
  GET_ALL_AGENCY: 'GET_ALL_AGENCY',

  GET_LIST_FREE_ESIM_BOOKING: 'GET_LIST_FREE_ESIM_BOOKING',
  BOOK_NEW_ESIM: 'BOOK_NEW_ESIM',
  GET_PACKAGES: 'GET_PACKAGES',
  // eSIM kèm gói
  GET_LIST_PACKAGED_ESIM: 'GET_LIST_PACKAGED_ESIM',
  BOOK_PACKAGED_ESIM: 'BOOK_PACKAGED_ESIM',
};
