export const REACT_QUERY_KEYS = {
  GET_MENU: 'GET_MENU',
  GET_DEBIT_LIMIT: 'GET_DEBIT_LIMIT',

  GET_LIST_FREE_ESIM_BOOKING: 'GET_LIST_FREE_ESIM_BOOKING',
  BOOK_NEW_ESIM: 'BOOK_NEW_ESIM',
  GET_PACKAGES: 'GET_PACKAGES',
  GET_ESIM_DETAILS: 'GET_ESIM_DETAILS',
};
