export const REACT_QUERY_KEYS = {
  GET_MENU: 'GET_MENU',
  GET_PACKAGES: 'GET_PACKAGES',

  // Danh sách eSIM
  GET_ESIM_WAREHOUSE_LIST: 'GET_ESIM_WAREHOUSE_LIST',
  GET_QR_CODE_SENT: 'GET_QR_CODE_SENT',
  GET_DETAIL_ESIM_WAREHOUSE: 'GET_DETAIL_ESIM_WAREHOUSE',
};
