export const QUERY_KEY = {
    GET_STOCK_TRANSFER_NUMBER: 'GET_STOCK_TRANSFER_NUMBER ',
    GET_FILE_UPLOAD: 'GET_FILE_UPLOAD',
    GET_STOCK_ISDN: 'GET_STOCK_ISDN',
    GET_REASON: 'GET_REASON',
    GET_STOCK_NUMBER: 'GET_STOCK_NUMBER',
};
