export const MESSAGE = {
  G01: 'Thêm mới thành công',
  G02: 'Cập nhật thành công',
  G03: 'Xóa thành công',
  G04: 'Bạn có chắc chắn muốn cập nhật không?',
  G05: 'Bạn có chắc chắn muốn xóa bản ghi không?',
  G06: 'Không được để trống trường này',
  G07: '${label} không đúng định dạng',
  G08: 'Đã duyệt thành công',
  G09: 'Từ chối thành công',
  G11: 'Đã mất kết nối!',
  G12: 'Thời gian tìm kiếm không vượt quá 30 ngày',
  G13: 'Kích thước ảnh phải nhỏ hơn 5MB',
  G14: 'File không đúng định dạng',
  G15: 'Bạn có chắc chắn muốn hủy bản ghi không?',
  G15b: (value: string) => `Bạn có chắc chắn muốn hủy ${value} không?`,
  G16: 'Sao chép thành công',
  G17: 'Đã hủy thành công',
  G17b: (value: string) => `Hủy ${value} thành công`,
  G30: 'Không được upload ảnh quá 500KB',
  G31: 'Vui lòng chọn hình ảnh có định dạng JPEG/JPG/PNG',
  G34: (value: number) => `Không được nhập vượt quá ${value} ký tự`,
  G36: (value: number) => `Nhập tối thiểu ${value} ký tự`,
  G37: (value: number) => `Trường bắt buộc nhập ${value} ký tự`,
  G38: 'Thiết bị chưa tích hợp camera',
  G39: 'Từ ngày 01/01/2025 không thể thay đổi thông tin với Giấy tờ tuỳ thân là Chứng minh nhân dân (9 số và 12 số)',
  G40: 'Vui lòng điền thông tin Ngày hết hạn giấy tờ hoặc Ngày hết hạn',
  G41: 'Không thể chuyển chủ quyền do số giấy tờ đang trùng với số giấy tờ đang có của thuê bao',
};
