export const REACT_QUERY_KEYS = {
  GET_MENU: 'GET_MENU',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_ALL_ROLES: 'GET_ALL_ROLES',
  GET_LIST_ORG_UNIT: 'GET_LIST_ORG_UNIT',
  GET_ALL_DEPARTMENTS: 'GET_ALL_DEPARTMENTS',
};
