export const REACT_QUERY_KEYS = {
  GET_MENU: 'GET_MENU',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_ALL_ROLES: 'GET_ALL_ROLES',
  GET_LIST_ORG_UNIT: 'GET_LIST_ORG_UNIT',
  GET_ALL_DEPARTMENTS: 'GET_ALL_DEPARTMENTS',
  GET_LIST_CATEGORY_PRODUCT: 'GET_LIST_CATEGORY_PRODUCT',
  GET_HISTORY_ISDN: 'GET_HISTORY_ISDN',
  GET_SEARCH_NUMBER: 'GET_SEARCH_NUMBER',
  GET_KEEP_ISDN: 'GET_KEEP_ISDN',
  GET_UN_KEEP_ISDN: 'GET_UN_KEEP_ISDN',
  PARTNER_CATALOG_LIST: 'PARTNER_CATALOG_LIST',
  PARTNER_CATALOG_LIST_INFINITY: 'PARTNER_CATALOG_LIST_INFINITY',

  // Danh mục
  LIST_OF_SERVICE_PACKAGE: 'LIST_OF_SERVICE_PACKAGE',
  LIST_OF_SERVICE_PACKAGE_VIEW: 'LIST_OF_SERVICE_PACKAGE_VIEW',
  GET_LIST_GROUP: 'GET_LIST_GROUP',
  GET_LIST_OBJECT_MENU: 'GET_LIST_OBJECT_MENU',
  GET_LIST_OBJECT_MENU_MOBILE: 'GET_LIST_OBJECT_MENU_MOBILE',
  GET_DETAIL_ROLE_BY_ID: 'GET_DETAIL_ROLE_BY_ID',
};
