export const REACT_QUERY_KEYS = {
  //common
  GET_MENU: 'GET_MENU',
  GET_PARAMS: 'GET_PARAMS',
  GET_ALL_PARAM: 'GET_ALL_PARAM',
  GET_PROFILE: 'GET_PROFILE',
  // User Management
  useGetDepartments: 'useGetDepartments',
  useSearchAllUsersPartner: 'useSearchAllUsersPartner',

  // Role Management
  GET_ALL_ROLES: 'GET_ALL_ROLES',
  ROLE_OBJECT_LIST: 'ROLE_OBJECT_LIST',
  GET_DETAIL_ROLE_BY_ID: 'GET_DETAIL_ROLE_BY_ID',
  GET_LIST_INTERNAL_EXPORT_PROPOSAL_SEND:
    'GET_LIST_INTERNAL_EXPORT_PROPOSAL_SEND',
  //UserGroupManagerKey
  GET_LIST_GROUP: 'GET_LIST_GROUP',
  GET_LIST_OPTION_USER_ACTIVE: 'GET_LIST_OPTION_USER_ACTIVE',
  GET_LIST_OPTION_ROLE_ACTIVE: 'GET_LIST_OPTION_ROLE_ACTIVE',
  //UserKey
  GET_LIST_GROUP_ACTIVE: 'GET_LIST_GROUP_ACTIVE',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_ALL_GROUP_USER: 'GET_ALL_GROUP_USER',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_ALL_ADN_BY_AGE: 'GET_ALL_ADN_BY_AGE',
  GET_ALL_ADN_BY_REGION: 'GET_ALL_ADN_BY_REGION',
  GET_USERS_BY_PERMISSION: 'GET_USERS_BY_PERMISSION',

  // Kit manager
  GET_LIST_KITS: 'GET_LIST_KITS',
  GET_LIST_LOCI_SELECT: 'GET_LIST_LOCI_SELECT',

  // Matching Rules
  GET_ALL_RULES: 'GET_ALL_RULES',
  GET_ALL_LOCIES: 'GET_ALL_LOCIES',

  // Request Management
  GET_ALL_PARAMS_REQUESTS: 'GET_ALL_PARAMS_REQUESTS',
  GET_ALL_REQUESTS: 'GET_ALL_REQUESTS',
  SUB_SYSTEM: 'SUB_SYSTEM',

  //AREA
  GET_LIST_PROVINCES: 'GET_LIST_PROVINCES',
  GET_LIST_DISTRICT: 'GET_LIST_DISTRICT',
  GET_LIST_WARD: 'GET_LIST_WARD',

  // Phân tích ADN SNP
  GET_TRANSITION_ID: 'GET_TRANSITION_ID',

  // Population
  GET_ALL_POPULATION: 'GET_ALL_POPULATION',

  //Tìm kiếm mẫu sủ dụng STR
  GET_MATCHING_RULES: 'GET_MATCHING_RULES',

  //Profile
  GET_USER_INFO: 'GET_USER_INFO',

  //Data Management
  GET_SUBJECT_ID: 'GET_SUBJECT_ID',

  //Drug Response
  GET_DRUG_RESPONSE: 'GET_DRUG_RESPONSE',
  GET_ALL_DRUG_RESPONSE: 'GET_DRUG_RESPONSE',

  //Medium Sick
  GET_MEDIUM_SICK: 'GET_MEDIUM_SICK',
  GET_ALL_MEDIUM_SICK: 'GET_ALL_MEDIUM_SICK',

  //ADNByAge
  GET_LIST_AGE: 'GET_LIST_AGE',

  //ADNByRegion
  GET_LIST_ADN_BY_REGION: 'GET_LIST_ADN_BY_REGION',

  // Exploration
  GET_UNIT_FILTER: 'GET_UNIT_FILTER',
  GET_DATA_SOURCE_FILTER: 'GET_DATA_SOURCE_FILTER',
  GET_SUBJECT: 'GET_SUBJECT',
  GET_COLLECTION_SAMPLE_BY_SUBJECT_ID: 'GET_COLLECTION_SAMPLE_BY_SUBJECT_ID',
  GET_COLLECTION_SAMPLE_BY_UNIT_ID: 'GET_COLLECTION_SAMPLE_BY_UNIT_ID',
  GET_FILE_SAMPLE_BY_COLLECTION_SAMPLE_ID:
    'GET_FILE_SAMPLE_BY_COLLECTION_SAMPLE_ID',
  GET_VARIANT_DETAIL_BY_SAMPLE_CODE: 'GET_VARIANT_DETAIL_BY_SAMPLE_CODE',
  GET_ALL_COLLECTION_FILE: 'GET_ALL_COLLECTION_FILE',
  GET_LIST_COLLECTION_UNIT: 'GET_LIST_COLLECTION_UNIT',
  GET_VARIANT_DETAIL_BY_ID: 'GET_VARIANT_DETAIL_BY_ID',
  GET_SNP_VARIANT_DETAIL_BY_ID: 'GET_SNP_VARIANT_DETAIL_BY_ID',
  GET_LIST_STR_VARIANT: 'GET_LIST_STR_VARIANT',
  GET_LIST_SNP_VARIANT: 'GET_LIST_SNP_VARIANT',

  GET_LIST_ADNPROVINCE: 'GET_LIST_ADNPROVINCE',
  GET_ALL_LIST_ADNPROVINCE: 'GET_ALL_LIST_ADNPROVINCE',

  //File collection ADN
  GET_LIST_FILE_COLLECTION_ADN: 'GET_LIST_FILE_COLLECTION_ADN',

  //Data source
  GET_LIST_DATA_SOURCE: 'GET_LIST_DATA_SOURCE',
  // Quản lý phả hệ
  GET_LIST_GRAPH: 'GET_LIST_GRAPH',
  GET_FAMILY_TREE: 'GET_FAMILY_TREE',
  GET_FAMILY_TREE_LV2: 'GET_FAMILY_TREE_LV2',

  // Danh sách adn profile
  GET_LIST_ADN_PROFILE: 'GET_LIST_ADN_PROFILE',

  // Gen
  GET_GRAPH_GEN: 'GET_GRAPH_GEN',

  //Local sample list
  GET_ALL_LOCAL_SAMPLE: 'GET_ALL_LOCAL_SAMPLE',

  //danh sách yêu cầu chuyển mẫu
  GET_ALL_TRANSFERRED_REQUEST_SAMPLE: 'GET_ALL_TRANSFERRED_REQUEST_SAMPLE',

  //ListOfDepartment
  GET_LIST_OF_DEPARTMENT: 'GET_LIST_OF_DEPARTMENT',

  // List of service package
  GET_LIST_OF_SERVICE_PACKAGE: 'GET_LIST_OF_SERVICE_PACKAGE',
  GET_VIEW_LIST_OF_DEPARTMENT: 'GET_VIEW_LIST_OF_DEPARTMENT',
  GET_PACKAGE_GROUP_LIST: 'GET_PACKAGE_GROUP_LIST',
  GET_PACKAGE_DETAIL: 'GET_PACKAGE_DETAIL',
  ADD_PACKAGE: 'ADD_PACKAGE',
  UPDATE_PACKAGE: 'UPDATE_PACKAGE',
  GET_CONNECTOR_LIST: 'GET_CONNECTOR_LIST',
  GET_PACKAGE_TYPE: 'GET_PACKAGE_TYPE',
  GET_PROFILE_TYPE: 'GET_PROFILE_TYPE',
  // PackageAuthorizationGET_VIEW_LIST_OF_DEPARTMENT
  GET_LIST_PACKAGE_AUTHORIZATION: 'GET_LIST_PACKAGE_AUTHORIZATION',
  GET_LIST_PACKAGES: 'GET_LIST_PACKAGES',
  GET_PCK_MAIN: 'GET_PCK_MAIN',
  GET_PCK_SUB: 'GET_PCK_SUB',
  GET_PCK_DETAIL: 'GET_PCK_DETAIL',
  GET_PCK_ADDON: 'GET_PCK_ADDON',
  // Product Catalog
  GET_LIST_PRODUCT_CATALOG: 'GET_LIST_PRODUCT_CATALOG',
  GET_DETAIL_PRODUCT_CATALOG: 'GET_DETAIL_PRODUCT_CATALOG',
  GET_LIST_PRODUCT_GROUP: 'GET_LIST_PRODUCT_GROUP',

  GET_LIST_CATEGORY_PRODUCT: 'GET_LIST_CATEGORY_PRODUCT',
  GET_LIST_CATEGOTY_TYPE: 'GET_LIST_CATEGOTY_TYPE',
  GET_DETAIL_CATEGORY_PRODUCT: 'GET_DETAIL_CATEGORY_PRODUCT',
  // Post check list
  GET_LIST_POST_CHECK_LIST: 'GET_LIST_POST_CHECK_LIST',
  GET_DETAIL_POST_CHECK_LIST: 'GET_DETAIL_POST_CHECK_LIST',
  GET_LIST_REASON_CUSTOMER: 'GET_LIST_REASON_CUSTOMER',
  GET_STATUS_AUDIT: 'GET_STATUS_AUDIT',
  GET_REASON_POST_CHECK_LIST: 'GET_REASON_POST_CHECK_LIST',
  // Parameter
  GET_LIST_PARAMETER: 'GET_LIST_PARAMETER',

  // tranferlist Number
  TRANSFER_LIST_NUMBER: 'TRANSFER_LIST_NUMBER',
  // Recall number
  GET_LIST_REVOKE_NUMBER: 'GET_LIST_REVOKE_NUMBER',

  // Assign number
  GET_LIST_ASSIGN_NUMBER: 'GET_LIST_ASSIGN_NUMBER',
  GET_DETAIL_ASSIGN_NUMBER: 'GET_DETAIL_ASSIGN_NUMBER',

  // GET_CRITERIA danh sách tiêu chí
  GET_CRITERIA: 'GET_CRITERIA',
  // GET_CENSORS danh sách người kiểm duyệt
  GET_CENSORS: 'GET_CENSORS',
  GET_LIST_OBJECT_MENU: 'GET_LIST_OBJECT_MENU',
  GET_LIST_OBJECT_MENU_MOBILE: 'GET_LIST_OBJECT_MENU_MOBILE',
  //REASON CATALOG
  GET_LIST_REASONS: 'GET_LIST_REASONS',
  GET_LIST_REASONS_TYPE: 'GET_LIST_REASON_TYPES',
  GET_ALL_REASON_CATALOG: 'GET_ALL_REASON_CATALOG',
  // Phone no inventory
  GET_LIST_PHONE_NUMBERS: 'GET_LIST_PHONE_NUMBERS',
  GET_HISTORY_PHONE_NUMBER: 'GET_HISTORY_PHONE_NUMBER',

  //PHONE NO. PREFIX
  GET_LIST_PHONE_NO_PREFIX: 'GET_LIST_PHONE_NO_PREFIX',
  POST_PHONE_NO_PREFIX: 'POST_PHONE_NO_PREFIX',
  GET_A_PHONE_NO_PREFIX: 'GET_A_PHONE_NO_PREFIX',

  // Supplier
  GET_SUPPLIER_LIST: 'GET_SUPPLIER_LIST',
  ADD_SUPPLIER: 'ADD_SUPPLIER',
  EDIT_SUPPLIER: 'EDIT_SUPPLIER',
  DELETE_SUPPLIER: 'DELETE_SUPPLIER',
  GET_SUPPLIER_DETAIL: 'GET_SUPPLIER_DETAIL',

  //CATEGORY-PROFILE
  GET_LIST_OF_PROFILES: 'GET_LIST_OF_PROFILE',

  // Censorship
  GET_CENSORSHIP_LIST: 'GET_CENSORSHIP_LIST',
  GET_CENSORSHIP_LIST_FOR_STAFF: 'GET_CENSORSHIP_LIST_FOR_STAFF',
  GET_APPROVAL_STATUS: 'GET_APPROVAL_STATUS',
  GET_SUBDOC_DETAIL: 'GET_SUBDOC_DETAIL',
  GET_APPROVE_REASON: 'GET_ALL_REASON',
  GET_AUDIT_REASON: 'GET_AUDIT_REASON',
  GET_ALL_REASON_CATALOG_SERVICE: 'GET_ALL_REASON_CATALOG_SERVICE',
  // UPLOAD SIM
  GET_LIST_UPLOAD_SIM: 'GET_LIST_UPLOAD_SIM',
  GET_LIST_UPLOAD_ORDER_NO: 'GET_LIST_UPLOAD_ORDER_NO',
  GET_LIST_UPLOAD_EXTEND_TRANSACTION: 'GET_LIST_UPLOAD_EXTEND_TRANSACTION',
  GET_LIST_PRODUCT_SIM: 'GET_LIST_PRODUCT_SIM',
  GET_LIST_SERIAL_LIST: 'GET_LIST_SERIAL_LIST',
  GET_FILE_SIM_TEMPLATE: 'GET_FILE_SIM_TEMPLATE',
  GET_LIST_ORG: 'GET_LIST_ORG',
  GET_LIST_PRODUCTS: 'GET_LIST_PRODUCTS',
  // Search Subscription
  GET_LIST_SUBSCRIPTION: 'GET_LIST_SUBSCRIPTION',
  GET_DETAIL_SUBSCRIPTION: 'GET_DETAIL_SUBSCRIPTION',
  GET_LIST_IMPACT_HISTORY: 'GET_LIST_IMPACT_HISTORY',
  GET_DETAIL_INFO_CHANGE: 'GET_DETAIL_INFO_CHANGE',
  GET_LIST_PACKAGE_HISTORY: 'GET_LIST_PACKAGE_HISTORY',
  GET_LIST_PACKAGE_REGIS: 'GET_LIST_PACKAGE_REGIS',
  GET_DETAIL_SUBSCRIBER_STATUS: 'GET_DETAIL_SUBSCRIBER_STATUS',
  GET_LIST_PACKAGE_CAPACITY: 'GET_LIST_PACKAGE_CAPACITY',
  GET_LIST_SUBSCRIBER_NO_IMPACT: 'GET_LIST_SUBSCRIBER_NO_IMPACT',
  GET_DETAIL_SEARCH_IMAGE: 'GET_DETAIL_SEARCH_IMAGE',
  GET_LIST_SUBSCRIBER_IMPACT_BY_FILE: 'GET_LIST_SUBSCRIBER_IMPACT_BY_FILE',
  GET_LIST_FEEDBACK_HISTORY: 'GET_LIST_FEEDBACK_HISTORY',
  GET_LIST_SMS_HISTORY: 'GET_LIST_SMS_HISTORY',

  // Export Transaction
  GET_EXPORT_TRANSACTION: 'GET_EXPORT_TRANSACTION',
  GET_REASON_EXPORT_TRANSACTION: 'GET_REASON_EXPORT_TRANSACTION',
  // GET_IMAGE
  GET_IMAGE: 'GET_IMAGE',
  // UPLOAD DIGITAL RESOURCE
  GET_FILE_UPLOAD_DIGITAL_SAMPLE: 'GET_FILE_UPLOAD_DIGITAL_SAMPLE',
  // danh muc so
  GET_STOCK_TYPE: 'GET_STOCK_TYPE',
  GET_LIST_WAREHOUSE_CATALOG: 'GET_LIST_WAREHOUSE_CATALOG',
  GET_DETAIL_WAREHOUSE_CATALOG: 'GET_DETAIL_WAREHOUSE_CATALOG',
  //ACTIVE-REQUEST_LIST
  GET_LIST_OF_ACTIVE_REQUEST_LIST: 'GET_LIST_OF_ACTIVE_REQUEST_LIST',
  GET_LIST_OF_ACTIVE_ASSIGN_LIST: 'GET_LIST_OF_ACTIVE_ASSIGN_LIST',
  GET_LIST_OF_ACTIVE_APPROVE_LIST: 'GET_LIST_OF_ACTIVE_APPROVE_LIST',
  GET_LIST_OF_APPROVE_STATUS: 'GET_LIST_OF_ACTIVE_APPROVE_LIST',
  GET_ND13: 'GET_ND13',
  // STOCK_OUT_FOR_DISTRIBUTOR
  GET_LIST_STOCK_OUT_FOR_DISTRIBUTOR: 'GET_LIST_STOCK_OUT_FOR_DISTRIBUTOR',
  GET_DETAIL_STOCK_OUT_FOR_DISTRIBUTOR: 'GET_DETAIL_STOCK_OUT_FOR_DISTRIBUTOR',

  // Đối tác
  ORDERS: 'ORDERS',
  PRODUCT_IN_ORDER: 'PRODUCT_IN_ORDER',
  PRODUCT_IN_ORDER_INFINITY_SCROLL: 'PRODUCT_IN_ORDER_INFINITY_SCROLL',
  GET_REASON: 'GET_REASON',
  GET_PARTNER_INFO: 'GET_PARTNER_INFO',
  PRODUCT_TYPE: 'PRODUCT_TYPE',
  // hạn mức đối tác
  PartnerCreditLimits: 'PartnerCreditLimits',
  GetListPartnerLimitsHistory: 'GetListPartnerLimitsHistory',
  getPartnerNoLimit: 'getPartnerNoLimit',
  GET_LIST_OF_REASON_REJECT: 'GET_LIST_OF_REASON_REJECT',
  // user kem don vi
  GET_LIST_USER_UNIT: 'GET_LIST_USER_UNIT',

  //  FILTER ORDER SALE
  GET_SALE_ORDER: 'GET_SALE_ORDER',

  // Partner
  PARTNER_CATALOG_LIST: 'PARTNER_CATALOG_LIST',
  PARTNER_CATALOG_LIST_INFINITY: 'PARTNER_CATALOG_LIST_INFINITY',

  // upload so
  // upload so
  GET_LIST_UPLOAD_NUMBER: 'GET_LIST_UPLOAD_NUMBER',
  GET_DETAIL_UPLOAD_NUMBER: 'GET_LIST_UPLOAD_NUMBER',
  GET_WAREHOUSE_EXPORT: 'GET_WAREHOUSE_EXPORT',

  // Congiguration management
  // upload
  // Congiguration management
  GET_CRITERIA_CONFIG_LIST: 'GET_CRITERIA_CONFIG_LIST',
  GET_ACTIVATION_CONFIG_LIST: 'GET_ACTIVATION_CONFIG_LIST',
  GET_TRANSFER_OF_OWNERSHIP_CONFIG_LIST:
    'GET_TRANSFER_OF_OWNERSHIP_CONFIG_LIST',
  // SIM replacement
  GET_ALL_ORGANIZATION: 'GET_ALL_ORGANIZATION',
  GET_SIM_REPLACEMENT_LIST: 'GET_SIM_REPLACEMENT_LIST',
  GET_SIM_REPLACEMENT_DETAIL: 'GET_SIM_REPLACEMENT_DETAIL',
  GET_ORGNIZATION_PARTNER: 'GET_ORGNIZATION_PARTNER',
  useGetObjectList: 'useGetObjectList',

  // lap phieu xuat

  useInfinityScrollProductList: 'useInfinityScrollProductList',
  // DS xuất nhập cho NPP
  GET_LIST_EXIM_DISTRIBUTOR: 'GET_LIST_EXIM_DISTRIBUTOR',
  GET_DETAIL_EXIM_DISTRIBUTOR: 'GET_DETAIL_EXIM_DISTRIBUTOR',

  // DS mã phiếu xuất
  GET_LIST_DELIVERY_NOTE: 'GET_LIST_DELIVERY_NOTE',
  GET_DETAIL_DELIVERY_NOTE: 'GET_DETAIL_DELIVERY_NOTE',

  STOCK_PRODUCT_SERIAL_KIT_STATUS: 'STOCK_PRODUCT_SERIAL_KIT_STATUS',
  STOCK_PRODUCT_SERIAL_STATUS: 'STOCK_PRODUCT_SERIAL_STATUS',

  //  INVENTORY_DETAIL
  INVENTORY_DETAIL: 'INVENTORY_DETAIL',
  GET_LIST_ORG_USE: 'GET_LIST_ORG_USE',

  // CHIẾT KHẤU
  GET_LIST_DISCOUNT_LIST: 'GET_LIST_DISCOUNT_LIST',
  GET_DETAIL_DISCOUNT: 'GET_DETAIL_DISCOUNT',
  PRODUCT_LIST_FILTER_CATID: 'PRODUCT_LIST_FILTER_CATID',

  //H2H ENTERPRISE
  GET_LIST_ENTERPRISES: 'GET_LIST_ENTERPRISES',
  GET_LIST_SALE_AND_AM: 'GET_LIST_SALE_AND_AM',
  GET_LIST_USERS: 'GET_LIST_USERS',
  GET_LIST_SALES: 'GET_LIST_SALES',
  GET_LIST_SUB: 'GET_LIST_SUB',
  GET_ENTERPRISE_DETAIL: 'GET_ENTERPRISE_DETAIL',

  // SUBSCRIBER IMPACT REPORT
  GET_SUBSCRIBER_IMPACT_REPORT: 'GET_SUBSCRIBER_IMPACT_REPORT',

  // ENTERPRISE REPRESENTATIVES
  GET_REPRESENTATIVES: 'GET_REPRESENTATIVES',
  GET_REPRESENTATIVE_DETAIL: 'GET_REPRESENTATIVE_DETAIL',
  GET_ENTERPRISE_HISTORY_LIST: 'GET_ENTERPRISE_HISTORY_LIST',
  GET_ENTERPRISE_HISTORY_DETAIL: 'GET_ENTERPRISE_HISTORY_DETAIL',
  // Feedback
  GET_FEEDBACK_TYPE: 'GET_FEEDBACK_TYPE',
  SEARCH_FEEDBACK_CSKH: 'SEARCH_FEEDBACK_CSKH',
  SEARCH_FEEDBACK_BO: 'SEARCH_FEEDBACK_BO',
  SEARCH_FEEDBACK_ASSIGN: 'SEARCH_FEEDBACK_ASSIGN',
  SEARCH_PRIORITY: 'SEARCH_PRIORITY',
  DETAIL_FEEDBACK: 'DETAIL_FEEDBACK',
  CHECK_ISDN_STATUS: 'CHECK_ISDN_STATUS',

  // Upload SIM Form
  GET_UPLOAD_SIM_FORM_LIST: 'GET_UPLOAD_SIM_FORM_LIST',
  GET_UPLOAD_SIM_FORM_dETAIL: 'GET_UPLOAD_SIM_FORM_dETAIL',
  GET_PRODUCT_LIST_UPLOAD_SIM: 'GET_PRODUCT_LIST_UPLOAD_SIM',
  GET_INFINITY_PO: 'GET_INFINITY_PO',
  TransactionSearchImportExportList: 'TransactionSearchImportExportList',

  // Classify special number
  GET_LIST_CLASSIFY_SPECIAL_NUMBER: 'GET_LIST_CLASSIFY_SPECIAL_NUMBER',
  GET_DETAIL_CLASSIFY_SPECIAL_NUMBER: 'GET_DETAIL_CLASSIFY_SPECIAL_NUMBER',

  // Đơn hàng online
  GET_LIST_ONLINE_ORDER: 'GET_LIST_ONLINE_ORDER',
  GET_DETAIL_ONLINE_ORDER: 'GET_DETAIL_ONLINE_ORDER',

  // Quản ý đơn hàng CS
  SEARCH_ORDER_CS: 'SEARCH_ORDER_CS',
  // Quản ý đơn hàng tại cửa hàng
  SEARCH_ORDER_AT_STORE: 'SEARCH_ORDER_CS',

  //CTKM
  GET_LIST_PROMOTION_HISTORY: 'GET_LIST_PROMOTION_HISTORY',
  GET_LIST_ACTIVE_PROMOTION: 'GET_LIST_ACTIVE_PROMOTION',
  GET_DETAIL_PROMOTION_HISTORY: 'GET_DETAIL_PROMOTION_HISTORY',
  ExportNumberPartnerKey: 'ExportNumberPartnerKey',
  ExportNumberPartnerOrderKey: 'ExportNumberPartnerOrderKey',

  GET_LIST_CHANNEL_FEEDBACK:'GET_LIST_CHANNEL_FEEDBACK',
  // Decrypt Operations
  DECRYPT_OPERATIONS_ID: 'DECRYPT_OPERATIONS_ID',
};
