export const MESSAGES = {
  MC0: 'Network error',
  MC1: 'Update success',
  MC2: 'Update failed',
  MS01: '${label} bắt buộc nhập',
  MS02: 'Mã số thuế không hợp lệ',
  MS03: '${label} không hợp lệ!',
  MS04: '${label} bắt buộc chọn',
  MS05: 'Không được để trống trường này',
  MS06: 'Đã mất kết nối!',
  MS07: (value: string) => `${value} phải khác nhau`,
};

export const MESSAGE = {
  G01: 'Bạn đồng ý lưu?',
  G02: 'Đã lưu thành công!',
  G03: 'Đề nghị kiểm tra dữ liệu đã nhập',
  G04: 'Bạn xác nhận xóa?',
  G05: 'Bạn xác nhận xóa?',
  G06: (value: string) => `Đã ${value} thành công!`,
  G07: (value: string) => `Đã xóa ${value} thành công!`,
  G08: 'Đã có lỗi xảy ra!',
  G09: 'Dữ liệu chưa thay đổi',
  G10: 'Dữ liệu cần xử lý chưa được chọn',
  G11: 'Đã mất kết nối!',
  G12: 'Bạn xác nhận phê duyệt?',
  G13: 'Bạn xác nhận từ chối phê duyệt?',
  G14: 'Bạn xác nhận từ chối và gửi trả yêu cầu?',
  G15: 'Đã có lỗi dữ liệu',
  G16: 'Bạn xác nhận gửi phê duyệt?',
  G17: 'Đã gửi thành công!',
  G18: 'Đã phê duyệt thành công!',
  G19: 'Đã từ chối và gửi trả yêu cầu thành công!',
  G20: 'Đã thực hiện không phê duyệt và gửi trả yêu cầu!',
  G21: 'Không được để trống trường này',
  G22: 'Tài khoản chưa được cấp quyền, vui lòng liên hệ cán bộ quản trị!',
  G23: 'Trường thông tin không đúng định dạng',
  G24: 'Phải chọn bản ghi cần xoá',
  G25: 'Sử dụng tối thiểu 8 ký tự và tối đa 24 ký tự. Bao gồm số, chữ thường, chữ in hoa và ký tự đặc biệt',
  G26: (value: string) =>
    `Tồn tại bản ghi ${value} không được phép xóa. Vui lòng kiểm tra lại`,
  G27: 'Bạn xác nhận vô hiệu hóa bản ghi?',
  G28: 'Bạn xác nhận kích hoạt bản ghi?',
  G29: 'Bạn xác nhận đăng xuất?',
  G30: 'Không được upload ảnh quá 500KB',
  G31: 'Vui lòng chọn ảnh có định dạng JPEG/JPG/PNG',
  G32: 'Vui lòng kiểm tra lại thông tin đăng nhập. Tài khoản sẽ bị khóa nếu nhập sai 5 lần',
  G33: 'Mã bản ghi đã tồn tại, vui lòng kiểm tra lại',
  G34: (value: number) => `Không được nhập vượt quá ${value} ký tự`,
  G35: (value: number) =>
    `Thời gian tìm kiếm để tải xuống vượt quá ${value} tháng, vui lòng kiểm tra lại	`,
  G36: (value: number) => `Nhập tối thiểu ${value} ký tự`,
  G37: (value: number) => `Trường bắt buộc nhập ${value} ký tự`,
  G37b: (value: number) => `Trường bắt buộc nhập ${value} ký tự số`,
  G38: 'Thiết bị chưa tích hợp camera',
};
